# Sintaxe básica do Pytorch

Assim como o NumPy, o Pytorch é uma biblioteca de processamento vetorial/matricial/tensorial. Operações sobre os tensores do Pytorch possuem sintaxe consideravelmente parecida com operações sobre tensores do NumPy.

Para mais informações sobre tensores em PyTorch, consulte a documentação: <br> https://pytorch.org/docs/stable/tensors.html



## Tipos de tensores 

Você pode criar tensores do PyTorch de inúmeras formas! Vamos ver primeiro os tipos de tensores que estão ao nosso dispor. Para isso, vamos converter listas comuns do Python em tensors do PyTorch.

Note que a impressão de tensores dos tipos ```float32``` e ```int64``` não vêm acompanhadas do parâmetro de tipo ```dtype```, visto que se tratam dos tipos padrão trabalhados pelo PyTorch.

In [1]:
import torch
lista = [ [1,2,3],
          [4,5,6] ]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

print('')
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

print('')
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)


torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


## Outras formas de instanciar tensores

### A partir de arrays Numpy
$torch.from\_numpy()$ 



In [2]:
# Quando geramos um tensor a partir do numpy ele seguirá o mesmo dtype dos dados

import numpy as np

arr = np.random.rand(3,4)
arr = arr.astype(int)
print(arr)
print(arr.dtype)

print('')
tns = torch.from_numpy(arr)
print(tns)
print(tns.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64


### Tensores inicializados
Essas funções recebem como parâmetro o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:

$torch.ones()$ -> Cria um tensor preenchido com zeros.

$torch.zeros()$ -> Cria um tensor preenchido com uns.

$torch.randn()$ -> Cria um tensor preenchido com números aleatórios a partir de uma distribuição normal.

In [3]:
tns1 = torch.ones(2, 3)
tns0 = torch.zeros(3, 5)
tnsr = torch.randn(3, 3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-0.2772,  0.2890, -0.5857],
        [ 0.2642,  0.8179, -0.8097],
        [-1.0301,  0.2276, -0.8573]])


### Tensor para array numpy

In [4]:
arr = tnsr.data.numpy()
print(arr)
print(type(arr))

[[-0.27723598  0.28904578 -0.58569604]
 [ 0.26419607  0.8178917  -0.8096605 ]
 [-1.0300869   0.22759172 -0.85732216]]
<class 'numpy.ndarray'>


## Indexação

De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, através da sintaxe de colchetes ```[]```.

In [5]:
# Indexar = selecionar | Fazendo selecções e transformações em uma tensor

print(tnsr)
tnsr[0,2] = -10
print('')
print(tnsr)
print('')
print(tnsr[:,2])

tensor([[-0.2772,  0.2890, -0.5857],
        [ 0.2642,  0.8179, -0.8097],
        [-1.0301,  0.2276, -0.8573]])

tensor([[ -0.2772,   0.2890, -10.0000],
        [  0.2642,   0.8179,  -0.8097],
        [ -1.0301,   0.2276,  -0.8573]])

tensor([-10.0000,  -0.8097,  -0.8573])


## Operações com tensores

A função ```.item()``` utilizada anteriormente extrai o número de um tensor que possui um único valor, permitindo realizar as operações numéricas do Python. Caso o item não seja extraído, operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas **ponto a ponto**, operando cada elemento ```(i, j)``` do tensor ```t1```, com o elemento ```(i, j)``` do tensor ```t2```.

In [8]:
tns1 = torch.randn(2,2,3)
tns2 = torch.ones(2,2,3)

print(tns1)
print(tns2)

print('')

print(tns1*tns2)
print('')
print(tns1+tns2)

tensor([[[ 0.6260,  0.6636,  0.2903],
         [-0.8096,  0.0219, -0.0846]],

        [[-1.1603,  0.7579,  0.5024],
         [ 1.8583,  0.7560,  0.0928]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

tensor([[[ 0.6260,  0.6636,  0.2903],
         [-0.8096,  0.0219, -0.0846]],

        [[-1.1603,  0.7579,  0.5024],
         [ 1.8583,  0.7560,  0.0928]]])

tensor([[[ 1.6260,  1.6636,  1.2903],
         [ 0.1904,  1.0219,  0.9154]],

        [[-0.1603,  1.7579,  1.5024],
         [ 2.8583,  1.7560,  1.0928]]])


## Função ```.size()``` e ```.view()```

Uma operações **importantíssima** na manipulação de tensores para Deep Learning é a reorganização das suas dimensões. Dessa forma podemos, por exemplo, **linearizar um tensor n-dimensional**.

In [10]:
print(tns2)
print('')

# Função .size() para verificar as dimensões do tensor
print(tns2.size())

print('')

# Função .view() utilizada para redimensionar o tensor
print(tns2.view(tns2.size(0), -1))

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

torch.Size([2, 2, 3])

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


## GPU Cast

Para que o seu script dê suporte a infraestruturas com e sem GPU, é importante definir o dispositivo no início do seu código de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisarmos subir valores na GPU, como os pesos da rede, os gradientes, etc.

In [12]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
  
print(device)
tns2 = tns2.to(device)
print(tns2)

cuda
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]], device='cuda:0')
